export class AdjusterProductIntent {
    mProductIntentId: number = 0;
    mInsuranceTypeId: string = '';
    mAdjusterCode: string = '';
    mAdjusterName: string = '';
    mStartDate: string = '';
    mEndDate: string = '';
    mSpId: number = 0;
    mSpubId: number = 0;
    mYearsOfExperience: number = 0;
    mAssignmentEligibility: string = '';
    mCommentId: number = 0;
    mComment: string = '';
    mTaxID: string = '';
    loggedInUserId: string = '';
    mInsuranceType: string = '';
    copyAdjusterExclutions: boolean = false;
    previousProductIntentId: number = 0;
}
